contact_us: /home
area_tag: span
areas_page: /areas-we-serve
company_name: 'Keyrenter Property Management Boise'
state: Idaho
address: "999 West Main Street, Suite 100\nBoise, ID 83702\n(208) 856-8000"
navigation_style: uppercase
banner: false
banner_classes: 'bg-gray-800 text-white p-4'
footer_case: uppercase
footer_second_title: 'Our Company'
footer_right: areas
footer_prefix: 'Property Management Websites by '
footer_ada: false
prefooter_enabled: false
prefooter_button_page: /home
fixed_enabled: false
testimonial: '0'
favicons: {  }
bg: {  }
video_bg: {  }
video_bg_poster: {  }
logo: {  }
logo_svg: {  }
places_api_key: AIzaSyB3yegJnmfQ6G7xhucyORVeMVY1tT8mXpc
place_id: ChIJ58IvGtv5rlQRZ1vwBQAXuCc
